//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMaster
    {
        public int BookingId { get; set; }
        public Nullable<int> RegId { get; set; }
        public Nullable<int> BusId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string City { get; set; }
        public string SeatNo { get; set; }
        public string TravelDate { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<int> BoardingID { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string PNRNo { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    }
}
