//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusMaster()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int BusId { get; set; }
        public string BusNo { get; set; }
        public string BustType { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<int> SeatColumn { get; set; }
        public Nullable<int> SeatRow { get; set; }
        public Nullable<int> BookedSeat { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
        public string BusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
    }
}
