//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public long CardID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CardType { get; set; }
        public string BankName { get; set; }
        public string CVVNo { get; set; }
        public string CardNo { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
