//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int DateID { get; set; }
        public System.DateTime Date { get; set; }
        public string DepartureTIme { get; set; }
        public string EstimatedTime { get; set; }
    }
}
